# Generated by Django 4.2.7 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atasks',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ftasks',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
